#!/usr/bin/env python3
"""
Generate a comparison HTML report from benchmark JSON.
Filters to only successful runs (no error).
"""
import json, os, sys
from datetime import datetime

def medal(r):
    return {1: '🥇', 2: '🥈', 3: '🥉'}.get(r, f'#{r}')

def bar(val, max_val, color='#222222'):
    pct = (val / max_val * 100) if max_val > 0 else 0
    return f'<div style="background:#eee;border-radius:3px;height:20px;width:100%"><div style="background:{color};width:{pct:.0f}%;height:20px;border-radius:3px;text-align:right;padding-right:6px;font-size:11px;line-height:20px;color:#fff;min-width:30px">{val}</div></div>'

json_path = sys.argv[1] if len(sys.argv) > 1 else "AUD-20260402-WA0018_benchmark_full.json"

with open(json_path, 'r') as f:
    all_data = json.load(f)

# Filter to only successful runs
runs = [r for r in all_data if not r.get('error')]
n = len(runs)

if n == 0:
    print("No successful runs found.")
    sys.exit(1)

audio_file = runs[0]['audio_file']
duration = runs[0]['duration_sec']
now = datetime.now().strftime("%B %d, %Y at %H:%M")

# Lower is better
for param in ['latency_sec', 'cost_hr_usd', 'rep_score', 'out_tokens']:
    sorted_runs = sorted(runs, key=lambda x: x.get(param, 0))
    for rank, r in enumerate(sorted_runs, 1):
        r[f'{param}_rank'] = rank

for param in ['word_count']:
    sorted_runs = sorted(runs, key=lambda x: x.get(param, 0), reverse=True)
    for rank, r in enumerate(sorted_runs, 1):
        r[f'{param}_rank'] = rank

for r in runs:
    r['overall_score'] = sum(r.get(f'{p}_rank', 0) for p in ['latency_sec', 'cost_hr_usd', 'rep_score', 'out_tokens', 'word_count'])

runs_sorted = sorted(runs, key=lambda x: x['overall_score'])

model_rows = ""
for rank_i, r in enumerate(runs_sorted, 1):
    lat = r.get('latency_sec', 0)
    rt = f"{lat/duration:.3f}x" if duration and lat else "—"
    model_rows += f"""
    <tr{' style="background:#fffde7;font-weight:600"' if rank_i == 1 else ''}>
        <td style="text-align:center;font-weight:700;font-size:1.2rem">{medal(rank_i)}</td>
        <td style="font-weight:600">{r['model_name']}</td>
        <td style="text-align:center">{r.get('tier', '—')}</td>
        <td style="text-align:center">{r.get('latency_sec', 0):.1f}s<br><span style="font-size:0.72rem;color:#888">{rt}</span></td>
        <td style="text-align:center">{r.get('out_tokens', 0):,}</td>
        <td style="text-align:center">${r.get('cost_hr_usd', 0):.4f}</td>
        <td style="text-align:center">{r.get('cost_run_usd', 0):.6f}</td>
        <td style="text-align:center">{r.get('word_count', 0):,}</td>
        <td style="text-align:center">{r.get('rep_score', 0):.4f}</td>
    </tr>"""

param_cards = ""
param_defs = [
    ("Latency ⚡", "Wall-clock transcription time. Lower = faster.", 'latency_sec', 's', '#2563eb'),
    ("Cost per Hour 💰", "USD per hour of audio. Calculated from token usage × pricing.", 'cost_hr_usd', '$', '#059669'),
    ("Output Tokens 📝", "Tokens generated by the model in the transcript.", 'out_tokens', '', '#d97706'),
    ("Word Count 📄", "Number of words in the output transcript.", 'word_count', '', '#7c3aed'),
    ("Repetition Score 🔄", "Lower = less hallucination/repetition.", 'rep_score', '', '#dc2626'),
]
for title, desc, key, unit, color in param_defs:
    vals = [(r['model_name'], r.get(key, 0)) for r in runs_sorted]
    max_val = max(v for _, v in vals) if vals else 1
    bars_str = "".join(f'<div style="margin:6px 0;font-size:0.9rem"><span style="font-weight:600;display:inline-block;width:180px">{m}</span>{bar(v, max_val, color)}</div>' for m, v in vals)
    param_cards += f"""
    <div class="param-card">
        <h4>{title}</h4>
        <p style="font-size:0.82rem;color:#555;margin-bottom:10px">{desc}</p>
        {bars_str}
    </div>"""

rank_rows = ""
for rank_i, r in enumerate(runs_sorted, 1):
    rank_rows += f"""
    <tr{' style="background:#fffde7;font-weight:600"' if rank_i == 1 else ''}>
        <td style="text-align:center;font-weight:700">{medal(rank_i)}</td>
        <td style="font-weight:600">{r['model_name']}</td>
        <td style="text-align:center">{r.get('latency_sec_rank', '—')}</td>
        <td style="text-align:center">{r.get('cost_hr_usd_rank', '—')}</td>
        <td style="text-align:center">{r.get('out_tokens_rank', '—')}</td>
        <td style="text-align:center">{r.get('word_count_rank', '—')}</td>
        <td style="text-align:center">{r.get('rep_score_rank', '—')}</td>
        <td style="text-align:center;font-weight:700">{r['overall_score']}</td>
    </tr>"""

best_all = runs_sorted[0]
fastest = min(runs, key=lambda x: x.get('latency_sec', 0))
cheapest = min(runs, key=lambda x: x.get('cost_hr_usd', 0))
most_detailed = max(runs, key=lambda x: x.get('out_tokens', 0))

# Side-by-side transcript comparison
transcript_rows = ""
for r in runs_sorted:
    t = r.get('transcript', '')[:600]
    t_short = t[:600] + '...' if len(r.get('transcript', '')) > 600 else t
    transcript_rows += f"""
    <div style="margin-bottom:20px">
        <h4 style="font-size:0.95rem;font-weight:700;margin-bottom:4px">{medal(runs_sorted.index(r)+1)} {r['model_name']}</h4>
        <div style="border:2px solid #000;padding:12px;font-family:'JetBrains Mono',monospace;font-size:0.78rem;line-height:1.4;max-height:250px;overflow-y:auto;background:#fafafa;white-space:pre-wrap">{t_short}</div>
    </div>"""

html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Gemini Model Comparison Report</title>
<link rel="preconnect" href="https://fonts.googleapis.com">
<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800;900&family=JetBrains+Mono:wght@400;500&display=swap" rel="stylesheet">
<style>
    * {{ box-sizing:border-box; margin:0; padding:0; }}
    body {{ background:#f5f6f8; color:#111; font-family:'Inter',system-ui,sans-serif; font-size:14px; padding:40px 24px; }}
    .container {{ max-width:1200px; margin:0 auto; }}
    h1 {{ font-size:2.4rem; font-weight:800; letter-spacing:-0.03em; margin-bottom:2px; }}
    .subtitle {{ color:#666; margin-bottom:6px; font-size:0.92rem; }}
    .meta {{ color:#888; margin-bottom:30px; font-size:0.82rem; }}
    h2 {{ font-size:1.4rem; font-weight:700; margin-top:40px; margin-bottom:14px; padding-bottom:6px; border-bottom:3px solid #000; }}
    table {{ width:100%; border-collapse:collapse; margin-bottom:30px; font-size:0.85rem; }}
    thead th {{ background:#000; color:#fff; padding:10px 12px; text-align:left; font-size:0.72rem; text-transform:uppercase; letter-spacing:0.04em; white-space:nowrap; }}
    tbody td {{ padding:10px 12px; border-bottom:1px solid #ddd; vertical-align:middle; }}
    tbody tr:hover {{ background:#f0f0f0; }}
    .param-card {{ border:2px solid #000; padding:18px 20px; background:#fff; margin-bottom:14px; }}
    .param-card h4 {{ font-size:0.9rem; font-weight:700; text-transform:uppercase; letter-spacing:-0.02em; margin-bottom:4px; }}
    .grid {{ display:grid; grid-template-columns:repeat(auto-fill,minmax(340px,1fr)); gap:14px; margin-bottom:30px; }}
    .verdict {{ border:4px solid #000; padding:20px 24px; background:#fff; }}
    .verdict h3 {{ font-size:1rem; font-weight:700; text-transform:uppercase; letter-spacing:-0.03em; }}
    .verdict .rec {{ font-size:1.3rem; font-weight:800; margin:4px 0; }}
    .verdict p {{ color:#555; font-size:0.85rem; }}
    .verdict.best {{ background:#000; color:#fff; }}
    .verdict.best h3 {{ color:#fff; }}
    .verdict.best .rec {{ color:#fff; }}
    .verdict.best p {{ color:#ccc; }}
    footer {{ margin-top:40px; padding-top:16px; border-top:2px solid #ddd; font-size:0.78rem; color:#888; }}
    .failed-note {{ background:#fef2f2; border:2px solid #dc2626; padding:12px 16px; margin-bottom:20px; font-size:0.85rem; }}
    .failed-note h4 {{ color:#dc2626; font-size:0.9rem; }}
</style>
</head>
<body>
<div class="container">

<h1>Model Comparison Report</h1>
<p class="subtitle">Gemini API — Punjabi Speech-to-Text Benchmarking</p>
<p class="meta">Generated {now} &bull; Audio: {audio_file} ({duration:.0f}s, {duration/60:.1f} min) &bull; {n} successful models out of {len(all_data)} total</p>

<div class="failed-note">
<h4>⚠ Models That Failed</h4>
{''.join(f'<div>• <strong>{r["model_name"]}</strong>: {r.get("error", "Unknown error")[:120]}</div>' for r in all_data if r.get('error'))}
</div>

<h2>Overall Rankings</h2>
<table>
<thead><tr>
<th>Rank</th><th>Model</th><th>Tier</th><th>Latency</th><th>Output Tokens</th><th>Cost/hr</th><th>Cost/Run</th><th>Words</th><th>Rep Score</th>
</tr></thead>
<tbody>
{model_rows}
</tbody>
</table>

<h2>Parameter Comparison</h2>
<div class="grid">
{param_cards}
</div>

<h2>Rankings by Parameter</h2>
<p style="font-size:0.82rem;color:#666;margin-bottom:8px">1 = best within this group. Lower overall score = better.</p>
<table>
<thead><tr>
<th>Overall</th><th>Model</th><th>Latency ⚡</th><th>Cost 💰</th><th>Tokens 📝</th><th>Words 📄</th><th>Rep 🔄</th><th>Score</th>
</tr></thead>
<tbody>
{rank_rows}
</tbody>
</table>

<h2>Verdict</h2>
<div class="grid" style="grid-template-columns:repeat(auto-fill,minmax(250px,1fr))">
    <div class="verdict best">
        <h3>🏆 Best Overall</h3>
        <p class="rec">{best_all['model_name']}</p>
        <p>Best balance of speed, cost, and output quality.</p>
    </div>
    <div class="verdict">
        <h3>⚡ Fastest</h3>
        <p class="rec">{fastest['model_name']}</p>
        <p>{fastest['latency_sec']:.1f}s total &bull; {fastest['rtf']:.3f}x real-time factor</p>
    </div>
    <div class="verdict">
        <h3>💰 Cheapest</h3>
        <p class="rec">{cheapest['model_name']}</p>
        <p>${cheapest['cost_hr_usd']:.4f}/hr &bull; ${cheapest['cost_run_usd']:.6f} total cost</p>
    </div>
    <div class="verdict">
        <h3>📝 Most Detailed</h3>
        <p class="rec">{most_detailed['model_name']}</p>
        <p>{most_detailed['out_tokens']:,} output tokens &bull; {most_detailed['word_count']:,} words</p>
    </div>
</div>

<h2>Transcript Comparison</h2>
{transcript_rows}

<footer>
<p>Generated by Comparison Report Script. Data from {json_path}</p>
</footer>
</div>
</body>
</html>"""

out_dir = os.path.dirname(os.path.abspath(json_path))
out_path = os.path.join(out_dir, "comparison_report.html")
with open(out_path, 'w', encoding='utf-8') as f:
    f.write(html)
print(f"✅ Report saved: {out_path}")
